-- Flyway ejecuta esto UNA sola vez, en orden (V1, V2, V3...), y lo registra
-- en su propia tabla de control (flyway_schema_history). Nunca se edita un
-- archivo ya aplicado -- cualquier cambio futuro es un V2__algo.sql nuevo.
--
-- Sintaxis adaptada a Oracle (distinta a la version H2 que teniamos antes):
--   BIGINT   -> NUMBER(19)     (Oracle no tiene BIGINT como tipo propio)
--   VARCHAR  -> VARCHAR2       (VARCHAR2 es el tipo de texto recomendado en Oracle)
--   DOUBLE   -> NUMBER         (para valores monetarios/decimales)
--   INTEGER  -> NUMBER(10)
--   GENERATED BY DEFAULT AS IDENTITY -- soportado desde Oracle 12c en adelante,
--   misma sintaxis ANSI que usabamos con H2.

CREATE TABLE categoria (
    id     NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(255)
);

CREATE TABLE etiqueta (
    id     NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(255)
);

CREATE TABLE producto (
    id           NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre       VARCHAR2(255) NOT NULL,
    precio       NUMBER        NOT NULL,
    stock        NUMBER(10)    NOT NULL,
    categoria_id NUMBER(19),
    CONSTRAINT fk_producto_categoria FOREIGN KEY (categoria_id) REFERENCES categoria (id)
);

CREATE TABLE producto_etiqueta (
    producto_id NUMBER(19) NOT NULL,
    etiqueta_id NUMBER(19) NOT NULL,
    PRIMARY KEY (producto_id, etiqueta_id),
    CONSTRAINT fk_producto_etiqueta_producto FOREIGN KEY (producto_id) REFERENCES producto (id),
    CONSTRAINT fk_producto_etiqueta_etiqueta FOREIGN KEY (etiqueta_id) REFERENCES etiqueta (id)
);

CREATE TABLE detalle_producto (
    id                 NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion_larga  VARCHAR2(255),
    garantia_meses     NUMBER(10) NOT NULL,
    producto_id        NUMBER(19),
    CONSTRAINT uk_detalle_producto_producto UNIQUE (producto_id),
    CONSTRAINT fk_detalle_producto_producto FOREIGN KEY (producto_id) REFERENCES producto (id)
);
