-- Flyway ejecuta esto UNA sola vez, en orden (V1, V2, V3...), y lo registra
-- en su propia tabla de control (flyway_schema_history). Nunca se edita un
-- archivo ya aplicado -- cualquier cambio futuro es un V2__algo.sql nuevo.

CREATE TABLE categoria (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255)
);

CREATE TABLE etiqueta (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255)
);

CREATE TABLE producto (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre       VARCHAR(255) NOT NULL,
    precio       DOUBLE       NOT NULL,
    stock        INTEGER      NOT NULL,
    categoria_id BIGINT,
    CONSTRAINT fk_producto_categoria FOREIGN KEY (categoria_id) REFERENCES categoria (id)
);

CREATE TABLE producto_etiqueta (
    producto_id BIGINT NOT NULL,
    etiqueta_id BIGINT NOT NULL,
    PRIMARY KEY (producto_id, etiqueta_id),
    CONSTRAINT fk_producto_etiqueta_producto FOREIGN KEY (producto_id) REFERENCES producto (id),
    CONSTRAINT fk_producto_etiqueta_etiqueta FOREIGN KEY (etiqueta_id) REFERENCES etiqueta (id)
);

CREATE TABLE detalle_producto (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion_larga  VARCHAR(255),
    garantia_meses     INTEGER NOT NULL,
    producto_id        BIGINT,
    CONSTRAINT uk_detalle_producto_producto UNIQUE (producto_id),
    CONSTRAINT fk_detalle_producto_producto FOREIGN KEY (producto_id) REFERENCES producto (id)
);
