-- Esquema INDEPENDIENTE para la version Hexagonal del proyecto (paquete
-- com.practica.crudpruebas.hexagonal). Tablas separadas con sufijo "_hex"
-- para que ambas versiones (por feature y hexagonal) convivan sin pisarse,
-- aunque representen el mismo dominio de negocio.

CREATE TABLE categoria_hex (
    id     NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(255)
);

CREATE TABLE etiqueta_hex (
    id     NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(255)
);

CREATE TABLE producto_hex (
    id           NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre       VARCHAR2(255) NOT NULL,
    precio       NUMBER        NOT NULL,
    stock        NUMBER(10)    NOT NULL,
    categoria_id NUMBER(19),
    CONSTRAINT fk_producto_hex_categoria FOREIGN KEY (categoria_id) REFERENCES categoria_hex (id)
);

CREATE TABLE producto_etiqueta_hex (
    producto_id NUMBER(19) NOT NULL,
    etiqueta_id NUMBER(19) NOT NULL,
    PRIMARY KEY (producto_id, etiqueta_id),
    CONSTRAINT fk_prod_etiq_hex_producto FOREIGN KEY (producto_id) REFERENCES producto_hex (id),
    CONSTRAINT fk_prod_etiq_hex_etiqueta FOREIGN KEY (etiqueta_id) REFERENCES etiqueta_hex (id)
);

CREATE TABLE detalle_producto_hex (
    id                 NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion_larga  VARCHAR2(255),
    garantia_meses     NUMBER(10) NOT NULL,
    producto_id        NUMBER(19),
    CONSTRAINT uk_detalle_hex_producto UNIQUE (producto_id),
    CONSTRAINT fk_detalle_hex_producto FOREIGN KEY (producto_id) REFERENCES producto_hex (id)
);
