-- Tablas para el caso complejo: Pedido (agregado raiz) + sus items
-- (value objects, incrustados via @ElementCollection -- por eso
-- pedido_item_hex NO tiene su propia columna "id").

CREATE TABLE pedido_hex (
    id    NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha TIMESTAMP NOT NULL
);

CREATE TABLE pedido_item_hex (
    pedido_id       NUMBER(19)    NOT NULL,
    producto_id     NUMBER(19)    NOT NULL,
    nombre_producto VARCHAR2(255) NOT NULL,
    cantidad        NUMBER(10)    NOT NULL,
    precio_unitario NUMBER        NOT NULL,
    CONSTRAINT fk_pedido_item_hex_pedido FOREIGN KEY (pedido_id) REFERENCES pedido_hex (id)
);
