-- Tabla de usuarios para Spring Security + JWT.
-- "password" guarda SIEMPRE un hash BCrypt (60 caracteres), nunca texto
-- plano -- por eso alcanza VARCHAR2(100) de sobra.
CREATE TABLE usuario (
    id       NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(100) NOT NULL,
    password VARCHAR2(100) NOT NULL,
    rol      VARCHAR2(20)  NOT NULL,
    CONSTRAINT uk_usuario_username UNIQUE (username)
);
