-- Esquema INDEPENDIENTE para la version Clean Architecture del proyecto
-- (paquete com.practica.crudpruebas.clean). Tabla propia con sufijo
-- "_clean", mismo criterio que "_hex" en V2: cada version arquitectonica
-- convive con su propio esquema, aunque representen el mismo negocio.
--
-- A diferencia de producto/producto_hex, esta version queda SIN relacion
-- a categoria/etiqueta a proposito: el foco de esta carpeta es mostrar la
-- estructura de Use Cases (un caso de uso = una clase), no repetir el
-- grafo relacional que ya esta cubierto en el esquema hexagonal.

CREATE TABLE producto_clean (
    id     NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(255) NOT NULL,
    precio NUMBER        NOT NULL,
    stock  NUMBER(10)    NOT NULL
);
